GET http://localhost:8080/api/v1/disciplina

###

POST http://localhost:8080/api/v1/disciplina
content-type: application/json

{
    "nomeDisciplina": "POO",
    "cargaHoraria": 72,
    "semestre": 6
}
###
GET http://localhost:8080/api/v1/disciplina/7a207ffb-6605-4ad0-8637-bf7ef31f7803
###
PUT  http://localhost:8080/api/v1/disciplina/7a207ffb-6605-4ad0-8637-bf7ef31f7803
Content-Type: application/json

{
    
    "nomeDisciplina": "topicos acccc",
    "cargaHoraria": 48,
    "semestre": 5   
}

###
DELETE http://localhost:8080/api/v1/disciplina/7a207ffb-6605-4ad0-8637-bf7ef31f7803
Content-Type: application/json

{
    "idDisciplina": "2",
    
}